### ISSUE TITLE
Player is already set up

### ISSUE THREAD

**Issue by ptkdev** [bitmovin/bitmovin-player-demo#13]
Hi,
I have single page application, how is correct flow to change video-url without refresh?
If i setup again player, received error: `Player is already set up`

**Comment by dweinber** [comment]
You can simply use the [`player.load(source)`](https://developer.bitmovin.com/hc/en-us/articles/115001561533-Bitmovin-Player-API-Documentation-v7#interfaces/playerapi.playerapi-1.html#load) API call on a set up player to switch to another source. Please feel free to reach out to support@bitmovin.com for questions.
